### ISSUE TITLE
I am strongly interested in your paper. Could you share you code? Thank you.

### ISSUE THREAD

**Issue by gengenkai** [cj4L/SSNM-Coseg#1]

**Comment by cj4L** [comment]
Thanks you very much for your attention. We plan to release the code after the meeting. If you want get it in advance, please contact me at chenjin9512@163.com

**Comment by zhangyuygss** [comment]
Any updates on the codes?

**Comment by cj4L** [comment]
Sorry for not responding in time, I will update the codes soon.

**Comment by taoshalang** [comment]
Is it convenient to upload training data?

**Comment by cj4L** [comment]
Hi, l:
Thank you for your concern about our work. Code you can find in https://github.com/cj4L/SSNM-Coseg/tree/ab1458f234280ba8d7d9e3afe9734bcf5ba27040


Best wishes!
Chen Jin
















At 2021-03-22 19:56:13, "taoshalang" ***@***.***> wrote:

Is it convenient to upload training data?
